### ISSUE TITLE
microhttpd removes reserved characters from passwords passed as GET response (effects PreAuth and BinAuth)

### ISSUE THREAD

**Issue by MarByteBeep** [nodogsplash/nodogsplash#476]
Hi,

When setting NoDogSplash to PreAuth-mode, the query string is encoded and uses commas as separators. However when testing this, I noticed that special characters such as "+" and "&" and even "," are all lost in the encoding process and simply get replaced with a space. 

This is not ideal for passwords :) 

Is there anything I'm doing wrong here? And is there a way to just let PreAuth use normal URL encoded query strings, as opposed to this comma separated string?

**Comment by bluewavenet** [comment]
@MarByteBeep 
The PreAuth Query string is sent to the PreAuth script as a command line argument and must be, and is, url encoded. It is the url decoding that is replacing the special characters.

A better title would be "PreAuth querystring url-decoding removes special characters".

You are not doing anything wrong here, the url decoding of the password in what I assume is your modified example PreAuth script is working as intended.

You could add your own code to scan the encoded password string for special characters though. You are already modifying it for password instead of email, so just one more step ;-)

The command line argument passed to PreAuth is url encoded - including the separator.

"comma space" as a separator is a safe choice to use and is currently hard coded into NDS.

**Comment by MarByteBeep** [comment]
Thanks a lot for your reply! Where should I add that code to scan for special characters? Because the encoded string that I received immediately after the GET request, already lost those characters. 

To observe this in action you can also simply rename the portal to something that contains these special characters, and then print out the raw query string in the portal bash script. Something like:

`echo “$1”`

The result will be url encoded, but you can see that all special chars have been replaced with %20. I need to be one step earlier in the process. 

Already thought of letting JavaScript modify the password string before submission; but that is out of the question as js is not an option with captive portals.

**Comment by MarByteBeep** [comment]
Add.:

I setup the following gatewayname:

`GatewayName No+Dog&Splash ,`

And preauth is set to:

`preauth /home/pi/login.sh`

and its contents are super simple:

```
#!/bin/sh

echo $1
```

Then when going to the portal, I get the following gatewayname:

`gatewayname%3dNo%20Dog%2c%20Splash%20%2c%2c%20`

which is:

`gatewayname=No Dog, Splash ,, `

The '+' becomes a space
The '&' becomes a comma-space
The ',' is not escaped and stays a comma, which is not helpful, since there is no way of knowing if the character is a comma or a separator.

**Comment by bluewavenet** [comment]
@MarByteBeep 
Any variables defined in PreAuth, like username, emailaddress and in your case password, are url encoded by the browser that CPD is using as it processes the get request. Generally the reserved characters "+" and "&" are replaced with a space in a get request. All the other reserved characters are ok I think.
Not much we can do about it as it is done by the client machine.
The special characters that are useable are:
!*'();:@=$,/?#[]
with the exception you cannot use ", " (comma and space together, in that order)

I am assuming you are using NDS v4.3.3, earlier versions might be different.

**Comment by bluewavenet** [comment]
Make sure you are using NDS v4.3.3 with the default login.sh (in /usr/lib/nodogsplash/)
In the config file, set the option login_option_enabled =1
ie in Openwrt:
```
uci set nodogsplash.@nodogsplash[0].login_option_enabled='1'
uci commit nodogsplash
service nodogsplash restart
```
Then put the string:
`!*'();:@=$,/?#[]`
as username.

**Comment by MarByteBeep** [comment]
> Generally the reserved characters "+" and "&" are replaced with a space in a get request.

What process is replacing this? Because I'd expect the client machine to properly URL encode all data in a GET request. I.e., replace + with %2B and & with %26. Is NDS replacing this somewhere in the code?

**Comment by MarByteBeep** [comment]
> Make sure you are using NDS v4.3.3 with the default login.sh (in /usr/lib/nodogsplash/)
> In the config file, set the option login_option_enabled =1
> ie in Openwrt:
> 
> ```
> uci set nodogsplash.@nodogsplash[0].login_option_enabled='1'
> uci commit nodogsplash
> service nodogsplash restart
> ```
> 
> Then put the string:
> `!*'();:@=$,/?#[]`
> as username.

I'll give that a try. Is it possible to customize that login though? I don't simply want username and password, but a whole bunch of other fields (that need proper encoding) as well. A little background on what it is that I'm trying to achieve...

The idea is to use the NDS portal as a configuration Access Point for a Raspberry Pi. For instance when the Pi lost its WiFi connection, an AP is created automatically in which the user can select a new SSID with password.  After submitting the form with the new SSID and password, the AP and portal are taken down and the Pi tries to reconnect to the internet using the new data. Aside from the SSID and password, I might need to be able to request other configuration data from the user as well (e.g., the name of the Raspberry). This needs to be properly encoded and there can be no assumptions on the input data (e.g., comma-space should be valid as well, as that can be part of the password or SSID).

**Comment by bluewavenet** [comment]
It is the difference between url-encoding and raw-url-encoding. I'll have a close look at the code...

**Comment by bluewavenet** [comment]
> The idea is to use the NDS portal as a configuration Access Point for a Raspberry Pi

The terminology used in the rpi world is incorrect and very often misleading.
NDS must run on a router and that router must be the ip gateway for the subnet. Whether that router also has a wireless radio or not, is irrelevant. NDS also requires a live Internet feed for the client CPD to function (although it can be fudged to work offline). Finally, an rpi does not make a very good router as it is optimised for workstation or station networking. Sorry for the rant :-D

PreAuth, a very cut down implementation of FAS, is a means of very flexibly customising the "splash page" with very little required in the way of resources such as flash space and ram, very important on low end routers. It is designed to be small compact and efficient.

If you have the resources, as you do on an rpi (apart from the slow network i/o), then FAS is the way to go if you want loads of fancy stuff.

**Comment by bluewavenet** [comment]
The issue does seem to be the client CPD browser doing its standard url-encoding for the get request.
It should be possible to allow post requests and then the form could be multipart/form-data.
But I am not sure what other consequences of this would be. A bit of investigation needed.

**Comment by MarByteBeep** [comment]
> The terminology used in the rpi world is incorrect and very often misleading.
> NDS must run on a router and that router must be the ip gateway for the subnet. Whether that router also has a wireless radio or not, is irrelevant. NDS also requires a live Internet feed for the client CPD to function (although it can be fudged to work offline). Finally, an rpi does not make a very good router as it is optimised for workstation or station networking. Sorry for the rant :-D

Haha no worries! I guess I fudged the functionality a bit by working offline and not using it for authentication at all. As mentioned before, I merely want to use the AP and NDS to configure the RPi. The data filled in the form will be sent to a bash script, which will then update internal config files based on that data.

> PreAuth, a very cut down implementation of FAS, is a means of very flexibly customising the "splash page" with very little required in the way of resources such as flash space and ram, very important on low end routers. It is designed to be small compact and efficient.

This is why the NDS seemed to be a perfect match for my purpose. I'm running it on a RPi Zero, so obviously I have no intentions in turning it into a full blown router ;)
 
> If you have the resources, as you do on an rpi (apart from the slow network i/o), then FAS is the way to go if you want loads of fancy stuff.

Well hopefully properly escaped GET variables isn't considered fancy. I guess I'm not fully capturing (pun intended ;)) the exact functionality and why this is going wrong. But I fail to grasp why the GET variables are the way they are. To me it seems that the NDS software is doing this and not the (Firefox) browser I'm using on my PC to connect to the AP. 

In your last comment you mention the option of trying POST. Sounds like a great idea, but how can I get them in my bash script? I assume $1 or something equivalent is not working.

Hopefully I can get this to work, as I'd love to avoid having to install a separate webserver on the RPi (PHP, Apache) in combination with full-blown FAS to be able to capture the properly escaped form data.

Again, thanks a lot for helping me out with this one!

**Comment by bluewavenet** [comment]
It is the standard for ALL browsers to url encode form data on a get request submission as application/x-www-form-urlencoded. This is what is causing your issue.


> Well hopefully properly escaped GET variables isn't considered fancy. 

Everything is "properly escaped".

Neither NDS nor the preauth script can be changed to fix this issue as it is a consequence of http standards.

With a post request however, the encoding can be switched off in html by setting enctype="multipart/form-data"
This means there will be no encoding at all so could be quite dangerous.

> I have no intentions in turning it into a full blown router

NDS will **not** work unless it is on a router.

> I merely want to use the AP and NDS to configure the RPi

If you just want to use NDS as a web server, you will probably come unstuck as the web server part is coded in NDS to be quite restricted in its functionality eg the post method is prohibited.
There is nothing to prevent you from using the libmicrohttpd library in your own code though.

**Comment by MarByteBeep** [comment]
At the risk of running in circles; I do have the feeling that we misunderstand each other :) This is how I see it. 

If a “+” is encoded into a space and a space is encoded in a space as well, I lose information. There is no way for me to convert the data back to the data the user entered; it’s ambiguous. Same with comma-space that is identical to the separator AND the “&” symbol. Please understand that this is the encoded string, not the decoded one. It’s the source data my script receives from the get request. To me something is not properly encoded when information is lost. And somehow I have a hard time understanding that it is the browser that does that. To my knowledge a browser encodes a “+” to %2B. Not %20. 

With these limitations I’m afraid I can’t use GET, since SSIDs and passwords can contain all kinds of character combinations. So I’ll try to get the post to work then; would it be possible for you to explain how I could read those post data in my bash script? Is it also passed as arguments?

**Comment by bluewavenet** [comment]
@MarByteBeep 
Ok, I concede defeat :-D
After some tests, it seems, as far as I can tell, that libmicrohttpd is doing it.
This will effect preauth and binauth, if either uses a text string containing "+" or "&" in the get request.
It will not effect a full FAS implementation, as this will not use libmicrohttpd. 
I have not had time to look in detail....

**Comment by bluewavenet** [comment]
@MarByteBeep 
libmicrohttpd (MHD) by default, unescapes encoded "+" as a space, for example. I don't think this is incorrect, just not what we want.
I can see how it is possible to define an unescape callback - I'll put it on my todo list!

**Comment by MarByteBeep** [comment]
Apologies for the delay in answering! Glad you were able confirm and localize the issue! Is it still possible for me to workaround this by using POST? If so, can you please point me in the right direction on how to do such a thing?

Thanks a lot!

**Comment by bluewavenet** [comment]
Both solutions require code changes within NDS. An unescape callback will fix this edge case and enabling post for preauth will be a useful enhancement but it would remain to be seen whether the unescape would be required with post as well. So no pointers for a work around I'm afraid.

As you are trying to use NDS only as a web server, you would be better off installing something like lighttpd instead, as the Zero has plenty of resources for this as well as a full suite of PHP modules if needed.

**Comment by MarByteBeep** [comment]
In all honesty, I wouldn't consider this an edge case, but a showstopper. The whole purpose of using PreAuth to fill in a login/password combination, cannot be trusted because of this bug.

Is there any ETA on this, and/or could I help you sorting out this problem?

As I'm really close to my goal (using NDS to get SSID/password combos), Im really reluctant to switching to another solution again. I'd rather wait for a fix. Unless of course this fix would take a long time ;)

**Comment by bluewavenet** [comment]
It will get fixed in due course.

Your idea is to make an html console to set up connection to a remote wifi.
You do know you can buy a travel router for less than the cost of your rpi hardware and this functionality will be built in?

Perhaps it would indeed be best for you to consider this issue as a "showstopper" and move on.

**Comment by MarByteBeep** [comment]
The RPi is built into a special device that needs to be able to run standalone anywhere, also without me. As soon as someone that has that device changes their WiFi password, the RPi needs to be able to accommodate that change as well by offering the Captive Portal. 

For now I’ll just ask them not to use passwords with those characters and wait for your fix :)

**Comment by MarByteBeep** [comment]
Also if you fix it; could you perhaps offer the standard URL escaping? So not separating the arguments with space comma but with & and encode all other special chars with %HH. That would be totally awesome. 

Thanks for all your work!

**Comment by bluewavenet** [comment]
@MarByteBeep 
It is not possible to use & as a delimiter as $redir could already contain some & chars as it could have its own querystring.
Anyway, the comma space issue is now fixed by PR #481 
This will be included in the next release but the new PreAuth script can be obtained from master for now.

**Comment by MarByteBeep** [comment]
Super awesome! And very fast. So now at least space comma can be part of a password. Thanks! I’ll go test it tomorrow. 

Just to confirm; this commit doesn’t fix the “+” and “&” to space replacements, right?

**Comment by MarByteBeep** [comment]
And as far as the & delimiter goes. I trust you understand the matter better than I do, so I’ll just go with the comma space delimiter 😊

**Comment by bluewavenet** [comment]
@MarByteBeep 
See PR #486 
This allows "+" and "&" characters to be used in passwords.
New release to follow shortly.

**Comment by MarByteBeep** [comment]
Super!!! I'll check it out as soon as possible. Thanks a lot for being so quick.

Cheers,

M

**Comment by MarByteBeep** [comment]
Hi Rob,

I updated and built the code and tried to run the NDS portal, however I now get the following error:

"Could not create web server: No such file or directory".

I use the same setup and settings as before. Before I dig into this more, do you happen to have any clue as to why this may happen?

**Comment by bluewavenet** [comment]
@MarByteBeep 

> I updated and built the code

Can you be specific?
ie are you using NDS v4.4.0?
Using an rpi with reaspbian?
What is in your NDS config file?

**Comment by MarByteBeep** [comment]
Sure thing!

* I use the latest version (pulled two days ago, I guess it is 4.4.0)
* RPI Zero W with Raspbian
* Config file is the one shipped with NDS with these changes

```
GatewayInterface wlan0
GatewayAddress 192.168.50.5
MaxClients 250
AuthIdleTimeout 480

WebRoot /home/pi/phone/portal

preauth /home/pi/phone/portal/portal.sh
```

But when commenting out the webroot path (so it uses the default), it still errors and exits.

As said, I haven't touched the other files anymore, I simply updated to the latest version, rebuilt everything and executed ```sudo nodogsplash``` and got this error. Any clue?

**Comment by bluewavenet** [comment]
@MarByteBeep 
Don't worry about making mistakes, it is the best way to learn.

A few points though:
 1. Your gateway address of 192.168.50.5 implies (but only implies) that you have your pi configured as a wireless access point. It must be a wireless router for NDS to work.
 2. When you download the source code it is essential you choose the release you require. If you just "pull it in" you will get master and that is just a current snapshot and might not work.
 3. **Last but not least!** The error you are getting is due to the fact the unescape callback uses an ash script that is **incompatible with Raspbian**. A fix is being worked on. (bare in mind that Raspbian support is only provided as a "minority" addon compared with OpenWrt with its hundreds of hardware/cpu targets, so needs people like you to test it :-D)  See #499 #500

**Comment by MarByteBeep** [comment]
Hi Rob!

Thanks again for the reply!

1) It indeed is an AP; and before the latest changes it was almost working as such on my RPi Zero W. The only thing that was problematic, was the missing unescape functionality. So I have high hopes of getting this to run as an AP.

2) Got it! I should wait for an official release then

3) This might be the problem! I'll wait for the next official release then, that includes all these fixes.

Cheers!


M

**Comment by bluewavenet** [comment]
@MarByteBeep 
The terminology used in the RPi world seems to be different to everywhere else and this causes all sorts of confusion!

> It indeed is an AP

**It MUST be a Wireless Router.** 
A wireless router is a router that has an access point built into it.

From the documentation:

> A router, by definition, will have two or more interfaces, at least one to connect to the wide area network (WAN) or Internet feed, and at least one connecting to the local area network (LAN).
> 
> Each LAN interface must also act as the Default IP Gateway for its LAN, ideally with the interface serving IP addresses to client devices using DHCP.

The Pi Zero W is slightly problematic in that it only has wifi and no ethernet. This means you must configure two virtual wifi interfaces, one as a "station" and one as an "access point", then configure IPv4 routing between them.

Can you confirm you have done all this configuration? This is an essential prerequisite.

**Comment by MarByteBeep** [comment]
Hi Rob,

As mentioned earlier; all was working fine before, except for the encoding part (as that information got lost)

To get this to work, I basically combined the two following tutorials:

https://www.raspberryconnect.com/projects/65-raspberrypi-hotspot-accesspoints/157-raspberry-pi-auto-wifi-hotspot-switch-internet

https://pimylifeup.com/raspberry-pi-captive-portal/

To setup the AdHoc network, I run the following script:

````
    echo "Creating Hotspot"
    ip link set dev "$wifidev" down
    ip a add 192.168.50.5/24 brd + dev "$wifidev"
    ip link set dev "$wifidev" up
    dhcpcd -k "$wifidev" >/dev/null 2>&1
    iptables -t nat -A POSTROUTING  -j MASQUERADE
    systemctl start dnsmasq
    systemctl start hostapd
    echo 1 > /proc/sys/net/ipv4/ip_forward
    echo "Starting nodogsplash captive portal"
    nodogsplash &
````

I'm not an expert on this matter, but I think the answer to your question is yes :)

**Comment by bluewavenet** [comment]
@MarByteBeep 
I do not now where an adhoc network would be involved. The wireless interface for clients must be in ap/master mode and a logical interface for Internet access must be in station mode. This is just not going to work in adhoc mode.... unless this is another example of Rpi world using different/incorrect terminology.
The most common use for adhoc mode is for wireless tethering or building mesh networks.

The pimpmylifeup tutorial is very old and very outdated and as such can be very misleading. I'm not saying it is out and out wrong, just that it has been left behind by so many changes in NDS since it was written. The probability of it working correctly must be quite low.

> "Could not create web server: No such file or directory".

You could try changing the first line of /usr/lib/nodogsplash/unsecape.sh

from
`#!/bin/sh`

to
`#!/bin/bash`
and make sure the file is executable.

Let me know if this fixes the issue.

**Comment by MarByteBeep** [comment]
Hi,

I'v tried the proposed change, but I still get that "no such file..." error. So I decided to try to get the v4.3.3 version again, to see if that gives me the same error. And it doesn't. When running that with

```
GatewayInterface wlan0
GatewayAddress 192.168.50.5
MaxClients 250
AuthIdleTimeout 480
```

and

```
preauth /etc/nodogsplash/login.sh
```

(the rest of the conf file is as shipped), NDS boots properly and doesn't show me that error. I can setup my RPi as Access Point and when trying to connect to it, it shows me the Captive Portal template login page (created in this script `/etc/nodogsplash/login.sh`)

So somewhere between v4.3.3 and the current version, something got borked. Would it be possible at all to actually let the error report the file and or directory that is missing? 

I can dig deeper and try newer repos until it fails. Not the best strategy, but as of now I'm basically working in the dark here :)

Cheers,


M

**Comment by MarByteBeep** [comment]
So I dug a bit deeper. I basically replaced unescape (in `http_microhttpd.c`) to simply:
```
size_t unescape(void * cls, struct MHD_Connection *c, char *src)
{
	return strlen(src);
}
```

and then in `main.c:270` I tested two cases:

```
	if ((webserver = MHD_start_daemon(MHD_USE_EPOLL_INTERNALLY | MHD_USE_TCP_FASTOPEN,
							config->gw_port,
							NULL, NULL,
							libmicrohttpd_cb, NULL,
							MHD_OPTION_CONNECTION_TIMEOUT, (unsigned int) 120,
							MHD_OPTION_LISTENING_ADDRESS_REUSE, 1,
							MHD_OPTION_UNESCAPE_CALLBACK, unescape,
							MHD_OPTION_END)) == NULL) {
		debug(LOG_ERR, "Could not create web server: %s", strerror(errno));
		exit(1);
	}
```
(i.e., the v4.4.0 version)

and 

```
	if ((webserver = MHD_start_daemon(MHD_USE_EPOLL_INTERNALLY | MHD_USE_TCP_FASTOPEN,
							config->gw_port,
							NULL, NULL,
							libmicrohttpd_cb, NULL,
							MHD_OPTION_CONNECTION_TIMEOUT, (unsigned int) 120,
							MHD_OPTION_LISTENING_ADDRESS_REUSE, 1,
							MHD_OPTION_END)) == NULL) {
		debug(LOG_ERR, "Could not create web server: %s", strerror(errno));
		exit(1);
	}
```
(which was the original v4.3.3 version).

The first case gives me that missing file error. The second case is able to startup the server. So, even with unescape doing absolutely nothing, I get that error when `MHD_OPTION_UNESCAPE_CALLBACK, unescape,` is passed as option to the server 'constructor'.

Any clue?

**Comment by bluewavenet** [comment]
@MarByteBeep 
PR #502 might fix it and is now merged into master.
I would much appreciate it if you could download the source from master on github and test this please - this will be v4.4.1beta
It is definitely a problem with running on Raspian/Debian as it is fine on OpenWrt

**Comment by MarByteBeep** [comment]
> @MarByteBeep
> PR #502 might fix it and is now merged into master.
> I would much appreciate it if you could download the source from master on github and test this please - this will be v4.4.1beta
> It is definitely a problem with running on Raspian/Debian as it is fine on OpenWrt

Sure thing; i'll give it a go!

**Comment by MarByteBeep** [comment]
It seems to be the same problem. As indicated in my previous comment, it seems that the creation of the webserver daemon fails when including that `MHD_OPTION_UNESCAPE_CALLBACK` option, even when `unescape` is just an empty function.

**Comment by MarByteBeep** [comment]
Just guessing randomly here; but perhaps it has something to do with the `libmicrohttpd` version I use. To build this on RPi I use:

```
sudo apt-get install libmicrohttpd-dev
```

Which gives me version 0.9.62-1 (which seems to be the latest)

**Comment by bluewavenet** [comment]
@MarByteBeep 
I'm running libmicrohttpd 0.9.69-1, so yours is not the latest, but I don't think that is the problem.

**Comment by bluewavenet** [comment]
@MarByteBeep 
From earlier:
```
    echo "Starting nodogsplash captive portal"
    nodogsplash &
```

Instead, try:
sudo nodogsplash -s -c /etc/nodogsplash/nodogsplash.conf

NDS is normally expected to run as root, so perhaps this is why it cannot run the unescape script.

I assume /usr/lib/nodogsplash/unescape.sh actually exists?

If it does try running in a terminal window:
`/usr/lib/nodogsplash/unescape.sh -url %21%22%23%24%0a`

and

`sudo /usr/lib/nodogsplash/unescape.sh -url %21%22%23%24%0a`

Any difference between the two?

You should should get:
`!"#$`

**Comment by MarByteBeep** [comment]
I’ll give it a try later! However I already call that parent script with sudo.

Also in my previous example I built nodogsplash without a call to the unescape script at all; and it still failed with said error. So I don’t think it is failing because of not being able to call that script.

**Comment by bluewavenet** [comment]
I think the issue here is that NDS needs to be run as a service. The easiest way to do this is to create a .deb package and install that.
A workaround seems to be to set debuglevel 2 if starting from the command line.
ie:
` sudo nodogsplash -d2 -s -c /etc/nodogsplash/nodogsplash.conf`

**Comment by MarByteBeep** [comment]
OMG... The -d2 option seems to do the trick indeed. Never expected that. The server seems to boot now. I can finally continue testing. So awesome. Thanks! And I'll report back if I run into more problems... :)

**Comment by bluewavenet** [comment]
@MarByteBeep 
The cause has been found to be a bug that causes a very subtle memory corruption that effects some combinations of operating system and hardware, yet does not seem to effect others (as indeed memory corruptions are apt to do).
Even the d2 workaround might lead to problems later...

**_It is now fixed in PR #511 and a new release will be issued in few days._**

Pending the new release, I would very much appreciate it if you could recompile from master,  test and report back ;-)
This will report itself as v4.4.1beta
https://github.com/nodogsplash/nodogsplash/archive/master.zip

**Comment by MarByteBeep** [comment]
Hi there!

I rebuilt the master and.... it works! Totally awesome. We are one step further.

So I retested the original problem: the encoding of special characters. The result is indeed different than before, but not quite there yet. I made an example in which I output the raw encoded string to the user and when supplying the following characters in a password, I get the following results:

```
Correct results
password=1234 -> password%3d1234
password=$ -> password%3d%24 
password=,  -> password%3d%2c%20
```

```
Incorrect results
password=% -> password%3d%5cx (= \x)
password=$$ -> password%3d12860 (=12860)
password=&,  -> password%3d (= empty)
```

So the comma-space and a single dollar sign, seems to work. But more than one dollar sign results in a very weird looking number; the % is replaced by simply "\x" and the "&" is lost.
Also passing a UTF-8 character like the Euro sign, results in this

```
password%3d%e2%82%ac
```

Not sure if that is correct though?

**Comment by bluewavenet** [comment]
@MarByteBeep 
I'm not sure what you mean by your examples. NDS now **_unescapes_** correctly as far as I can see. The escaping is done by the browser.

I just tested here on OpenWrt with `login_option_enabled 1`
All working.

You can test directly by running the unescape script (this is exactly what NDS does).
Here is what I get on both OpenWrt and OpenSuse:

```
root@BlueWave:~# echo $(/usr/lib/nodogsplash/unescape.sh -url password%3d%25)
password=%
root@BlueWave:~# echo $(/usr/lib/nodogsplash/unescape.sh -url password%3d%24%24)
password=$$
root@BlueWave:~# echo $(/usr/lib/nodogsplash/unescape.sh -url password%3d%26)
password=&
root@BlueWave:~# echo $(/usr/lib/nodogsplash/unescape.sh -url password%3d%e2%82%ac)
password=€
root@BlueWave:~#
```

Is your locale set in Raspbian to utf-8? (using raspi-config?)
Is utf-8 also the default in your browser?

**Comment by bluewavenet** [comment]
@MarByteBeep 
The browser default locale should not matter because the login script sends the html header:
`	<meta charset=\"utf-8\"> `

**Comment by MarByteBeep** [comment]
Hi Rob

Let me try to elaborate by super simple example:

Get a vanilla configuration file and set preauth path to some sh script location. The sh script looks like this

```
#!/bin/sh

echo $1
```

That's it. It simply outputs the encoded querystring.

Now when going to the NDS, I get the following output:

```
%3fclientip%3d192.168.50.171%2c%20gatewayname%3dNoDogSplash%2c%20redir%3dhttp%3a%2f%2fcaptive.apple.com%2fhotspot-detect.html
```

All looks good.

Now change the gatewayname to `NoDog$$Splash` and observe the output:

```
%3fclientip%3d192.168.50.171%2c%20gatewayname%3dNoDog1859Splash%2c%20redir%3dhttp%3a%2f%2fcaptive.apple.com%2fhotspot-detect.html
```

Some magical number (1859) has been added instead. And the weird thing is, this number seems to change every time I access that portal. (memory corruption?)

With this simple example, I didn't even use the brower's POST or GET. So I added some output to the unescape function, trying to locate the problem and noticed the following:

```
Escaped string=/nodogsplash_preauth/?clientip=192.168.50.171&gatewayname=NoDog$$Splash&redir=http%3a%2f%2fcaptive.apple.com%2fhotspot-detect.html
Unescaped string=/nodogsplash_preauth/?clientip=192.168.50.171&gatewayname=NoDog3138Splash&redir=http://captive.apple.com/hotspot-detect.html
```

So I tried your example

```
echo $(/usr/lib/nodogsplash/unescape.sh -url password=$$)
```
Which resulted in
```
password=605
```

Trying 

```
echo $(/usr/lib/nodogsplash/unescape.sh -url password=%)
```
gave me

```
unescape.sh line 18: printf: missing hex digit for \n
password=\x
```

The exact issue I'm observing. 

The problem seems to be that the unescape method is used to escape the string. 

Hope my problem now makes sense? :)

**Comment by bluewavenet** [comment]
@MarByteBeep 
I have been testing too.
Note: I don't have anything to run raspbian on.
Testing on **_Openwrt 18.06.6 and OpenWrt Snapshot_** (development master) everything works.
if $$ is entered, NDS receives %24%24 from the client CPD browser and unescape.sh returns $$ 

All good.

However on OpenWrt 19.07.0
if "$$" is entered, NDS receives $$ from the cilent CPD browser and unescape.sh returns a magic random number because it is trying to unescape something that is not escaped.

This means the problem is the browser. When connected to OpenWrt 19.07.0, it does not escape the $$ before sending to NDS in the query string.

Very odd. Might this be something to do with locale on the NDS device? - still testing.

**Comment by MarByteBeep** [comment]
> This means the problem is the browser. When connected to OpenWrt 19.07.0, it does not escape the $$ before sending to NDS in the query string.

This sounds like the exact same problem I have, since the escaped string that is first received in the unescape function contains the unescaped version of $$:

```
escaped string = /nodogsplash_preauth/?clientip=192.168.50.171&gatewayname=NoDog$$Splash&redir=http%3a%2f%2fcaptive.apple.com%2fhotspot-detect.htm
```

I test on Raspbian with and iPhone (iOS) trying to connect to NDS.

**Comment by bluewavenet** [comment]
I found the area of the problem but away for the afternoon. 
It is login.sh somehow causing it.
On 19.07.0 the browser ignores the code page setting in the html. There must be some weirdness in the way ash on 19.07.0 is interpreting the code in login.sh.
It is probably trivial once I see the actual problem. This evening UTC I will look in detail.

**Comment by bluewavenet** [comment]
@MarByteBeep 
Numerous false starts later (but some genuine fixes later), I think I have it!
Remember this? :

> Just guessing randomly here; but perhaps it has something to do with the libmicrohttpd version I use. To build this on RPi I use:
> 
> sudo apt-get install libmicrohttpd-dev
> 
> Which gives me version 0.9.62-1 (which seems to be the latest)

Well on Openwrt 19.07.0 I had libmicrohttpd version 0.9.62, same as you, and I get magic numbers for $$ etc.
I upgraded to v0.9.69-1, the version I have on OpenWrt snapshot, and IT WORKS.
So the solution seems to be that libmicrohttpd needs to be version 0.9.69 or above.

**_Please tell me it works for you too!_**

**Comment by bluewavenet** [comment]
@MarByteBeep 
https://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.69.tar.gz

**Comment by MarByteBeep** [comment]
Hi Rob!

Thanks for all the puzzling ;) I did some puzzling as well to build that libmicrohttpd on my RPi. After numerous trials and errors I managed to build the library. Also NDS builds fine without warnings.

These are my build steps (for all you future NDS on RPi users out there):

Get https://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.69.tar.gz and unzip it in `~\libmicrohttpd`

```bash
# get dependencies for libmicrohttpd build system
sudo apt-get install automake
sudo apt-get install texinfo

# build and install libmicrohttpd
cd ~\libmicrohttpd
chmod +x configure
sudo ./configure
sudo make
sudo make install

# update shared library links and cache
sudo /sbin/ldconfig -v

# build and install nodogsplash
cd ~
git clone https://github.com/nodogsplash/nodogsplash.git
cd ~/nodogsplash
make
sudo make install
```

So I tested it and.....

IT WORKS! *

Passwords seem to be properly escaped and unescaped. This is awesome! I'll do some more testing! Thanks a lot!

*) yes... there is always a but... I noticed one area where the magic number $ is still occuring: it is the initial query string that contains the gateway name:

`/nodogsplash_preauth/?clientip=192.168.50.171&gatewayname=NoDog$$Splash&redir=http%3a%2f%2fcaptive.apple.com%2fhotspot-detect.htm`

That one still produces magic numbers. However they don't appear anymore when the browser sends the password in a GET request. Any idea what that might be?

**Comment by bluewavenet** [comment]
@MarByteBeep 
Looking good for a documentation update! ;-)
You should download the source files for the release version required rather than default to a git clone of master. In fact the download of both NDS and MHD could be automated with wget.

> the magic number $ is still occurring: it is the initial query string that contains the gateway name

That is fixed in some updates I have here. will be committing them soon.

**Comment by MarByteBeep** [comment]
How would you rewrite my example so that it uses `wget`?

> You should download the source files for the release version required rather than default to a git clone of master

When I do:

```
git clone https://github.com/nodogsplash/nodogsplash.git --branch v4.4.0
```

Unfortunately I still have that problem with the webserver not booting. So I used the master (for now).

I tested it a bit more and ran into a different problem: I cannot reach the AP when I set `WebRoot`. By default the conf file uses `/etc/nodogsplash/htdocs`. I set this to some home folder:

```bash
WebRoot /home/pi/phone/portal
```

When doing that, nothing works anymore. Whereas this *has* worked before. That WebRoot folder exists. The custom conf options that I use:

```
GatewayInterface wlan0
GatewayAddress 192.168.50.5
MaxClients 250
AuthIdleTimeout 480

WebRoot /home/pi/phone/portal
preauth /home/pi/phone/portal/portal.sh
```

That's it, the rest are defaults. Any clue?

**Comment by bluewavenet** [comment]
@MarByteBeep 
Allowing version to be added into your build steps is purely for documentation purposes.
Previous version branches are not usually kept, instead release tags are used, so I think you could use git clone in that way instead. 

However the OpenWrt build system uses github codeload to download the version tar.gz
From the OpenWrt makefile:
`PKG_SOURCE_URL:=https://codeload.github.com/nodogsplash/nodogsplash/tar.gz/v$(PKG_VERSION)?`
This could be incorporated into a Debian build script that uses wget to retrieve the release tar.gz
